### ISSUE TITLE
gif

### ISSUE THREAD

**Issue by VadimDez** [VadimDez/ng2-order-pipe#1]
![ng2-order-pipe](https://cloud.githubusercontent.com/assets/3748453/22164327/08764608-df57-11e6-9c90-075aeca26fd6.gif)

**Comment by hellodpk** [comment]
It is better to add live working example. Even [https://vadimdez.github.io/ngx-order-pipe/](https://vadimdez.github.io/ngx-order-pipe/) does not helps.

I expect some [stackblitz](https://stackblitz.com/) working demo or [plunker](https://plnkr.co/) demo.
