### ISSUE TITLE
Update README.md with new classname

### ISSUE THREAD

**Issue by prateek0103** [VadimDez/ng2-order-pipe#4]
Current docs ask user to import `Ng2FOrderPipeModule` whereas `Ng2OrderModule` is the exported classname.

Kudos for an awesome pipe.

**Comment by VadimDez** [comment]
@prateek0103 thank you! Didn't notice that.

**Comment by Errvald** [comment]
It's still wrong, `Ng2FOrderPipeModule` should be `Ng2OrderModule`.

**Comment by ismailnural** [comment]
Still same
