### ISSUE TITLE
Expression not fetching the value

### ISSUE THREAD

**Issue by jestintab** [VadimDez/ng2-order-pipe#8]
hi, my expression is key:value pair. its not sorting or fetching the desire value.
json link:http://aljedad.com/api/sforder/9i3njlbu8_categories/?_view=json
I need to get the value values.priority.value for sorting. Please help how it can be done?

**Comment by VadimDez** [comment]
Probably your filter should look like this:
``ts
let filter = {
  values: {
    priority: {
      value: 'value'
    }
  }
}
```
